#!/bin/bash

DIRNAME=$1
ZAEFILES=`sudo ls $DIRNAME/*.zae $DIRNAME/*.xml $DIRNAME/*.dae`

for f in $ZAEFILES
do
    openrave.py --database inversekinematics --robot=$f --numiktests=1000 --iktype=translationxaxisangle4d
    sleep 1
done
