#!/bin/bash

clear && clear

DIRNAME=./robotfiles
ZAEFILES=`sudo ls $DIRNAME/*.zae $DIRNAME/*.xml $DIRNAME/*.dae`

for f in $ZAEFILES
do
    openrave.py --database inversekinematics --robot=$f --numiktests=1000
    sleep 1
done
